name: Build Custom Image for Release

on:
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') && !contains(github.event.commits.*.message, '[ci skip]') }}

    strategy:
      matrix:
        platform: [amd64, arm64, universal]

    steps:
      - name: ğŸ” Checkout code
        uses: actions/checkout@v4

      - name: ğŸ¦„ Set up Qemu for Docker
        uses: docker/setup-qemu-action@v2

      - name: ğŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ”‘ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: âš“ Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          platforms: linux/${{ matrix.platform }}
          cache-from: type=registry,ref=maisuier/mastodon:${{ github.event.release.tag_name }}-${{ matrix.platform }}
          cache-to: type=inline
          tags:  maisuier/mastodon:${{ github.event.release.tag_name }}-${{ matrix.platform }}
        if: ${{ matrix.platform == 'arm64' }}

      - name: âš“ Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          platforms: linux/${{ matrix.platform }}
          cache-from: type=registry,ref=maisuier/mastodon:${{ github.event.release.tag_name }}-${{ matrix.platform }}
          cache-to: type=inline
          tags: |
            maisuier/mastodon:${{ github.event.release.tag_name }}-${{ matrix.platform }}
        if: ${{ matrix.platform == 'amd64' }}
        
      - name: âš“ Build and push universal image
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64, linux/arm64
          cache-from: type=registry,ref=maisuier/mastodon:${{ github.event.release.tag_name }}
          cache-to: type=inline
          tags: |
            maisuier/mastodon:${{ github.event.release.tag_name }}
        if: ${{ matrix.platform == 'universal' }}
